feature: combine - some fix and add example
YusukeHosonuma/SwiftPrettyPrint pull request #121
Opened 2020-12-01 06:52 UTC by YusukeHosonuma

2020-12-01 06:58 UTC, YusukeHosonuma commented on Example/Podfile
> +pod "SwiftPrettyPrint", :path => "../", :branch => "feature/combine-example", :configuration => "Debug"
This will change to `master` at before merge.

2020-12-06 13:02 UTC, sahara-ooga requested changes
I found some minor typo in a comment.
As a whole, This looks awesome.

2020-12-06 13:02 UTC, sahara-ooga commented on Sources/Public/CombineExtension.swift
> +            option.prefix = nil // Prepend duplicat output.
Fixing typo.

```suggestion
            option.prefix = nil // prevent duplicate output.
```

2020-12-07 06:18 UTC, YusukeHosonuma commented on Sources/Public/CombineExtension.swift
> +            option.prefix = nil // Prepend duplicat output.
Thx!

2020-12-07 10:13 UTC, sahara-ooga approved these changes

2020-12-07 10:15 UTC, sahara-ooga approved these changes

2020-12-09 03:33 UTC, po-miyasaka approved these changes
LGTM!!

2020-12-09 08:36 UTC, merged