update README for 1.2.0
YusukeHosonuma/SwiftPrettyPrint pull request #145
Opened 2021-01-15 05:06 UTC by YusukeHosonuma

resolved #144

2021-01-28 12:33 UTC, sahara-ooga requested changes

2021-01-28 12:33 UTC, sahara-ooga commented on README.md
> +SwiftPrettyPrint output log files to follows automaticully when running **iOS Simulator** or **macOS**.
I think we should correct the verb tense and typo. 

```suggestion
SwiftPrettyPrint outputs log files to the following files automatically when running **iOS Simulator** or **macOS**.
```

2021-01-28 12:33 UTC, sahara-ooga commented on README.md
> +So you can read its from other tools such as `tail` or `grep` and others.
Isn't this what you're trying to say, is this?

```suggestion
So you can read them from other tools such as `tail` or `grep` and others.
```

2021-01-29 09:51 UTC, YusukeHosonuma commented
Thanks for review with suggestion changed 👍

2021-01-29 09:51 UTC, merged